### ISSUE TITLE
Modify the data access link label for the OER granule metadata

### ISSUE THREAD

**Issue by Yuanjie0913** [cedardevs/feedback#1]
In the data access links for the OER granule metadata, the direct link for the low resolution files is mentioned as 'Unknown'. The link works fine though. Can this be changed to something like 'Preview'?
e.g. https://data.noaa.gov/onestop/#/collections/granules/AWbw8ZJ0HtVRBOAZkCRD

**Comment by zebdelk** [comment]
There are two parts to this.

1. From what I can see of the underlying data, the metadata for that link is missing both name and description attributes. Updating that metadata would be the best way to change the text of the link.

2. Production is on version 2.0.4, which doesn't recognize the protocol video:mp4. "Unknown" is the default we use for when we do not have specific rules for rendering a protocol. This is already fixed in version 2.1, which correctly identifies that protocol and labels it "Video" (assuming no link name or description is provided).

**Comment by dneufeldcu** [comment]
An example video record displayed in version 2.1 with linkProtocol set to "video:mp4"
[link](https://sciapps.colorado.edu/onestop/collections/granules/AWoDIedFve2FB-bXY19g?q=EX1706&i=AWoDIedFve2FB-bXY19g)

**Comment by Yuanjie0913** [comment]
Thanks! Looks good. When will this version be merged to the production?

**Comment by dneufeldcu** [comment]
I estimate 2-4 weeks.

**Comment by dneufeldcu** [comment]
Fixed and in production as of v2.1.2
